version: "3"
services:
  nginx:
    image: nginx:1.19.6
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/log:/var/log/nginx"
      - "./wordpress/static:/var/www/html"
    ports:
      - "8001:80"
      - "80:80"
    depends_on:
      - wordpress
    container_name: nginx
    networks:
      - frontend
  wordpress:
    image: wordpress:5.6-php7.4-fpm
    depends_on:
      - db
    volumes:
      - "./wordpress:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      container_name: wordpress
    networks:
      - frontend
  db:
    image: mariadb:10.5.8
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: exampleroot
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    container_name: db
    networks:
      - frontend
volumes:
  wordpress:
networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24